### ISSUE TITLE
manager_version should match the tagged version

### ISSUE THREAD

**Issue by frosty-geek** [osism/cfg-cookiecutter#417]
Looking at the initial setup docs for [seed](https://docs.osism.tech/deployment/seed.html) nodes there is no mention how to specify the OSISM Release we want to deploy.

the tagged version of the cookiecutter repo lists [manager_version](https://github.com/osism/cfg-cookiecutter/blob/c6431cb1f18e02c194fbfbceacc08633ae1b18ce/cookiecutter.json#L17) as "latest".

[release.osism.tech](https://release.osism.tech/) tells you how to manually set the version you want to deploy instead of latest

**Comment by berendt** [comment]
When you run the cookiecutter, you will be asked for the version of the manager. If you enter 4.2.0 instead of latest, this will be used accordingly.

The tag on this repository with the 4.2.0 is a tag and not a branch. Therefore, the version there is also set by default to latest and not to 4.2.0.

The tag only means that this tagged status works together with the 4.2.0 release.

**Comment by berendt** [comment]
@frosty-geek Please have a look at #418.
